#!/usr/bin/env bash
# 0-change_your_home_IP
# Simple way to set localhost and facebook.com in /etc/hosts

# Requires root.
if [[ $EUID -ne 0 ]]; then
    echo "Please run as root"
    exit 1
fi

# Overwrite /etc/hosts with the required entries
cat <<EOF > /etc/hosts
127.0.0.2    localhost
8.8.8.8      facebook.com
EOF
