#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts /tmp/hosts.tmp

sed 's/^127\.0\.0\.1\s*localhost/127.0.0.2\tlocalhost/' /tmp/hosts.tmp > /etc/hosts

if grep -q "facebook.com" /etc/hosts; then
    cp /etc/hosts /tmp/hosts.tmp
    sed 's/.*facebook\.com.*/8.8.8.8\tfacebook.com/' /tmp/hosts.tmp > /etc/hosts
else
    echo "8.8.8.8	facebook.com" >> /etc/hosts
fi
